add_newline = false
format = "$all"

[line_break]
disabled = true

[character]
success_symbol = "[→](bold green)"
error_symbol   = "[→](bold red)"

[directory]
truncation_length = 5
truncation_symbol = "../"

[time]
disabled = false
time_range = "22:00:00-06:00:00"

[cmd_duration]
min_time = 60_000

[cmake]
symbol = "△ "
